name: ProjectEuler
version: 0.1.0.0
github: "Javran/ProjectEuler"
license: MIT
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2019 Javran Cheng"
description: "Javran's ProjectEuler Workspace"

extra-source-files:
- README.md

data-files:
- data/*.txt
- data/*.yaml
- data/*.mustache

dependencies:
- aeson
- arithmoi
- array
- base
- bytestring
- combinat
- containers
- criterion
- cyclotomic
- data-ordlist
- deepseq
- directory
- dlist
- file-embed
- filepath
- foldl
- lens
- lifted-base
- math-functions
- MemoTrie
- microstache
- monad-control
- MonadRandom
- mtl
- parsec
- petbox
- profunctors
- PSQueue
- scientific
- set-cover
- split
- strict
- system-filepath
- terminfo
- text
- text-show
- time
- transformers-base
- turtle
- union-find
- unordered-containers
- utility-ht
- vector
- yaml

_exec-ghc-options: &exe-ghc-options
  - -threaded
  - -O2
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  pet:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - ProjectEuler
    ghc-options: *exe-ghc-options

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - QuickCheck
      - ProjectEuler
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -main-is Spec
