{-
  DO NOT EDIT: this file is generated by templater.

  Last sync: 2019-06-10 05:39:59.966523796 UTC
 -}
module ProjectEuler.AllProblems
  ( allProblems
  ) where

import qualified Data.IntMap.Strict as IM

import ProjectEuler.Types

import ProjectEuler.Problem1
import ProjectEuler.Problem24

allProblems :: IM.IntMap Problem
allProblems =
  IM.fromList
    [ (1, ProjectEuler.Problem1.problem)
    , (24, ProjectEuler.Problem24.problem)
    ]
